//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceReferenceEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SLWFC")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Empleado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Empresa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEmpleado.IServiceEmpleado")]
    public interface IServiceEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/Add", ReplyAction="http://tempuri.org/IServiceEmpleado/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceReferenceEmpleado.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL_MVC.ServiceReferenceEmpleado.Result Add(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/Add", ReplyAction="http://tempuri.org/IServiceEmpleado/AddResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> AddAsync(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/Update", ReplyAction="http://tempuri.org/IServiceEmpleado/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceReferenceEmpleado.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL_MVC.ServiceReferenceEmpleado.Result Update(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/Update", ReplyAction="http://tempuri.org/IServiceEmpleado/UpdateResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> UpdateAsync(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/Delete", ReplyAction="http://tempuri.org/IServiceEmpleado/DeleteResponse")]
        PL_MVC.ServiceReferenceEmpleado.Result Delete(string NumeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/Delete", ReplyAction="http://tempuri.org/IServiceEmpleado/DeleteResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> DeleteAsync(string NumeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/GetAll", ReplyAction="http://tempuri.org/IServiceEmpleado/GetAllResponse")]
        PL_MVC.ServiceReferenceEmpleado.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/GetAll", ReplyAction="http://tempuri.org/IServiceEmpleado/GetAllResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/EmpresaGetAll", ReplyAction="http://tempuri.org/IServiceEmpleado/EmpresaGetAllResponse")]
        PL_MVC.ServiceReferenceEmpleado.Result EmpresaGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/EmpresaGetAll", ReplyAction="http://tempuri.org/IServiceEmpleado/EmpresaGetAllResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> EmpresaGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/GetById", ReplyAction="http://tempuri.org/IServiceEmpleado/GetByIdResponse")]
        PL_MVC.ServiceReferenceEmpleado.Result GetById(string NumeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpleado/GetById", ReplyAction="http://tempuri.org/IServiceEmpleado/GetByIdResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> GetByIdAsync(string NumeroEmpleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmpleadoChannel : PL_MVC.ServiceReferenceEmpleado.IServiceEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmpleadoClient : System.ServiceModel.ClientBase<PL_MVC.ServiceReferenceEmpleado.IServiceEmpleado>, PL_MVC.ServiceReferenceEmpleado.IServiceEmpleado {
        
        public ServiceEmpleadoClient() {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL_MVC.ServiceReferenceEmpleado.Result Add(ML.Empleado empleado) {
            return base.Channel.Add(empleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> AddAsync(ML.Empleado empleado) {
            return base.Channel.AddAsync(empleado);
        }
        
        public PL_MVC.ServiceReferenceEmpleado.Result Update(ML.Empleado empleado) {
            return base.Channel.Update(empleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> UpdateAsync(ML.Empleado empleado) {
            return base.Channel.UpdateAsync(empleado);
        }
        
        public PL_MVC.ServiceReferenceEmpleado.Result Delete(string NumeroEmpleado) {
            return base.Channel.Delete(NumeroEmpleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> DeleteAsync(string NumeroEmpleado) {
            return base.Channel.DeleteAsync(NumeroEmpleado);
        }
        
        public PL_MVC.ServiceReferenceEmpleado.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PL_MVC.ServiceReferenceEmpleado.Result EmpresaGetAll() {
            return base.Channel.EmpresaGetAll();
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> EmpresaGetAllAsync() {
            return base.Channel.EmpresaGetAllAsync();
        }
        
        public PL_MVC.ServiceReferenceEmpleado.Result GetById(string NumeroEmpleado) {
            return base.Channel.GetById(NumeroEmpleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReferenceEmpleado.Result> GetByIdAsync(string NumeroEmpleado) {
            return base.Channel.GetByIdAsync(NumeroEmpleado);
        }
    }
}
